### ISSUE TITLE
How to generate ground planes and scores for new dataset?

### ISSUE THREAD

**Issue by rockylu1995** [Zengyi-Qin/TLNet#5]
How are ground planes and scores(front views) generated? Could you provide the ground planes and scores for Kitti testing data?

**Comment by Zengyi-Qin** [comment]
For practical use, plane aX+bY+cZ+d=0 can be fixed as a=0, b=-1, c=0, d=camera_height(~1.65m in KITTI), which means the plane is just the plane supporting the wheels. This works for most scenarios.

The scores are the front-view confidence map. Consider the ground truth 2D bounding box with (center_u, center_v, width, height). The region within center_u-alpha \times width ~ center_u+alpha \times width & center_v-alpha \times height~center_v+alpha \times height is with score=1.0. We choose alpha=0.25.

The scores are used to train a front-view score predictor in the network. So in inference we do not need them.

**Comment by rockylu1995** [comment]
Thanks for your reply. One more question, the plane you provided for each image in kitti validation dataset are different and they are not fixed. What methods you used to calculate planes for validation dataset. Thank you!

**Comment by rockylu1995** [comment]
Hi, zengyi. I checked the code and I did not found the code about the front-view score predictor you mentioned and I found you covered little details about this in paper. Could you provide the algorithm details about this predictor. And for new testing data, mini-batches producing and anchor producing should be performed first, right? Therefore, I need to run gen_mini_batches.py on test images first, right?

**Comment by Zengyi-Qin** [comment]
(1)  We use the ground planes provided by AVOD's authors. 
      Actually their ground planes are partly from Xiaozhi Chen's PAMI paper 
      https://arxiv.org/pdf/1608.07711.pdf
      The planes can be caculated as follows: 
      estimating depth from RGB image.
      converting depth to 3D point clouds.
      segmenting the RGB pixels belonging to the road. 
      ---- this actually enables you to identify the 3D points of the road.
      using ransac algorithm to fit a plane from those 3D points.
    OR using the IMU data of the vehicle. The IMU provides the motion
       details that can be used to fit the plane the vehicle is running on.
    Anyway, the ground plane is just a part that should exist but is missing
    in KITTI dataset. There're many ways to recover it.

**Comment by Zengyi-Qin** [comment]
avod/core/models/rpn_model.py
search for "self.pred_score_2d" and it would lead you to the right place.

The score has shape (B, H, W, C)=(1, 12, 39, 2), where the last channel indicates a binary classification.
It's 32times smaller than the input image with size (1, 384, 1248, 3). The score comes from conv5 of the VGG16 model.

**Comment by rockylu1995** [comment]
Thanks for your reply. I will check the code.

**Comment by rockylu1995** [comment]
For new test frames, which script we need to run? run_inference.py or run_evalution.py? When I set the argument named "--data_split" to "test", I got error messages from kitti_dataset.py.

**Comment by Zengyi-Qin** [comment]
There're a few things to prepare for testing on new images.
- rename the left images as 000000.png, 000001.png ..... xxxxxx.png and place them into `image_2`. Do the same for right images but place them into `image_3`.
- modify the `val.txt'` so that 000000, 000001, xxxxxx occupy each line.
- run with "--data_split=val". In this way the script will read the indices in `val.txt` you just modified.

Anyway, just organize your new data in the original structure. No need to generate mini-batches, where we place anchors on the road plane then store them in the disk. When testing on new data, just use the generated anchors. The anchors in each file are almost the same, the difference caused by the pose of road plane is really small

**Comment by rockylu1995** [comment]
Thanks for your reply. You mentioned in the paper your team used the front view estimation to reduce searching space. And based on your reply, which means you generate all anchors first and then cut the redundant anchors, right?
