### ISSUE TITLE
How to reproduce the results?

### ISSUE THREAD

**Issue by zklgame** [Zengyi-Qin/TLNet#7]
Hi, thank you for sharing your impressive work!
I tried to reproduce the results by training the avod_model from the beginning, using pyramid_cars_with_aug_example.config. But my results are obviously worse than your official 
results. So I wonder is there any strategy to improve it? Followings are my results:

```
car_detection AP: 75.690880 70.246086 62.367188
car_detection_BEV AP: 23.874300 19.502445 16.575666
car_heading_BEV AP: 20.519953 16.949894 14.588367
car_detection_3D AP: 14.506160 12.164421 10.431151
car_heading_3D AP: 12.352068 10.488585 9.109080

car_detection AP: 75.690880 70.246086 62.367188
car_detection_BEV AP: 60.144279 44.793129 40.709419
car_heading_BEV AP: 51.869225 39.059811 35.779518
car_detection_3D AP: 54.263695 41.946064 36.740337
car_heading_3D AP: 46.786346 36.563709 32.363617
```

Also the results using the official ckpt:

```
car_detection AP: 83.077690 74.790451 66.324509
car_detection_BEV AP: 26.550058 20.508518 17.202452
car_heading_BEV AP: 23.459908 18.359175 15.576450
car_detection_3D AP: 16.633070 13.154133 10.710773
car_heading_3D AP: 14.627363 11.763421 9.660733

car_detection AP: 83.077690 74.790451 66.324509
car_detection_BEV AP: 62.658787 45.780983 40.430977
car_heading_BEV AP: 54.947575 40.726665 36.163692
car_detection_3D AP: 58.832096 43.159737 37.216217
car_heading_3D AP: 51.667618 38.398491 33.348675
```

Looking forward to your reply.

**Comment by Zengyi-Qin** [comment]
Thank you for your interest. 

- In the training process the pipeline will save its model files every 2000 steps. Not every output can reach the reported numbers. I would suggest you to test the saved model weights between step 100000 and 120000, where the best results will approximate the reported numbers. 

- If still not, please try to follow the training process described in the paper, which means the front-view anchor generation stage (the `TRAIN_SCORE_2D` flag in `avod/core/models/rpn_model.py`) should be first trained before training the RPN stage (the `TRAIN_RPN_3D` flag in `avod/core/models/rpn_model.py`) and RCNN stage (the `TRAIN_REFINE` flag in `avod/core/models/avod_model.py`). Set the first one to True and the other two to False, wait for the model to converge (4000 steps are enough), and then turn on the last two to train the whole network.

**Comment by zklgame** [comment]
> Thank you for your interest.
> 
> * In the training process the pipeline will save its model files every 2000 steps. Not every output can reach the reported numbers. I would suggest you to test the saved model weights between step 100000 and 120000, where the best results will approximate the reported numbers.
> * If still not, please try to follow the training process described in the paper, which means the front-view anchor generation stage (the `TRAIN_SCORE_2D` flag in `avod/core/models/rpn_model.py`) should be first trained before training the RPN stage (the `TRAIN_RPN_3D` flag in `avod/core/models/rpn_model.py`) and RCNN stage (the `TRAIN_REFINE` flag in `avod/core/models/avod_model.py`). Set the first one to True and the other two to False, wait for the model to converge (4000 steps are enough), and then turn on the last two to train the whole network.

Wow, thank you for the details. I will follow your suggestion. And if any improvement, I will update it here.

**Comment by zklgame** [comment]
I followed the training process suggestion and trained the model, but got even worse results:

```
car_detection AP: 62.299545 53.878777 47.832932
car_detection_BEV AP: 21.106590 16.269199 15.210639
car_heading_BEV AP: 19.376863 14.828157 13.830922
car_detection_3D AP: 13.050710 10.543097 9.509156
car_heading_3D AP: 12.119148 9.628718 8.685186
IOU == 0.5:
car_detection AP: 62.299545 53.878777 47.832932
car_detection_BEV AP: 48.537529 36.642570 31.184212
car_heading_BEV AP: 43.542011 32.671326 27.999035
car_detection_3D AP: 44.633247 31.717834 29.564072
car_heading_3D AP: 40.419353 28.524727 26.679234
```

It seems so hard to reproduce a better result.

**Comment by Zengyi-Qin** [comment]
I see. I think I know what the problem was. In the middle right of page 5 of our paper, we mentioned that the very last step should be using SGD to train for an extra 20K iterations. This is crucial for the results. I feel sorry for not reminding you in the last reply.

- You can change this line to 'gradient_descent {`:
https://github.com/Zengyi-Qin/TLNet/blob/d24b8b3fef9602e92ddc9477413a75d528a12323/avod/configs/pyramid_cars_with_aug_example.config#L99

- and load the model you just trained, and train for an extra 20K iterations.

**Comment by zklgame** [comment]
Oh, thank you for reminding me. I will check the Paper carefully and try again.

**Comment by zklgame** [comment]
Hi, here are my final results:
```
car_detection AP: 77.914734 69.687599 62.861244
car_detection_BEV AP: 22.030567 17.558327 15.387341
car_heading_BEV AP: 19.404621 15.691990 13.911944
car_detection_3D AP: 13.895358 11.667142 9.940385
car_heading_3D AP: 12.271743 10.478580 9.043906
IOU == 0.5:
car_detection AP: 77.914734 69.687599 62.861244
car_detection_BEV AP: 59.180595 42.913448 38.835045
car_heading_BEV AP: 52.469299 38.385563 34.992634
car_detection_3D AP: 53.756969 39.698811 35.324047
car_heading_3D AP: 47.677593 35.517818 31.854099
```
